# Generated by Django 5.0.3 on 2024-07-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_customuser_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(blank=True, default='images/pfp.webp', null=True, upload_to='images/'),
        ),
    ]
