# Generated by Django 5.0.3 on 2024-07-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_customuser_temp_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='temp_pass',
        ),
    ]
