# Generated by Django 5.0.3 on 2024-07-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='reply_ids',
            field=models.ManyToManyField(blank=True, related_name='replies', to='email_sender.email'),
        ),
    ]
