# Generated by Django 5.0.3 on 2024-07-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0004_email_reply_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
